# -*- coding: utf-8 -*-
"""GOVAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sUUfkOnGAauoLhyB66SsJTjVGtK7LWj6

# **GovAI: Your AI Partner for Understanding and Shaping Government**

## **Introduction :**
This code uses xAI's Grok-beta and LangChain to provide an interactive way to learn about government, enabling users to explore complex topics and foster civic understanding.

Setting Up the Environment
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install anthropic openai langchain-openai httpx==0.27.2 --force-reinstall --quiet

import os
os.kill(os.getpid(), 9)

from google.colab import userdata

# Store your API key. Replace with your actual key
api_key = 'xai-IXEtNnbggbWGcL5U3fjnYSAt5I6eotgVrphnXZVS2dZv9cvQyad3oRPFfobRjN9OkLbVIpEJMedfEutX'

"""This code uses LangChain to connect to the xAI API, initializes the 'grok-beta' language model, sends a prompt about government, and prints the AI's response"""

from langchain_openai import OpenAI
import os

# Set up LangChain for OpenAI
os.environ["OPENAI_API_KEY"] = 'xai-IXEtNnbggbWGcL5U3fjnYSAt5I6eotgVrphnXZVS2dZv9cvQyad3oRPFfobRjN9OkLbVIpEJMedfEutX'
os.environ["OPENAI_API_BASE"] = "https://api.x.ai/v1"

# Initialize the OpenAI model
llm = OpenAI(
    model="grok-beta",
    max_tokens=50,
)

# Generate text
prompt = "what is government."
output = llm(prompt)
print(f"AI-generated response:n{output}")

"""This Python code queries the xAI Grok API to get an AI-powered explanation

"""

import requests


# Define the endpoint and headers
url = "https://api.x.ai/v1/chat/completions"
headers = {
   "Authorization": f"Bearer {api_key}",
   "Content-Type": "application/json"
}
data = {
   "model": "grok-beta",
   "messages": [
       {
           "role": "system",
           "content": "You are a minister, guide me appropriately"
       },
       {
           "role": "user",
           "content": "Explain youth importance to me"
       }
   ],
   "stream": False,
   "temperature": 0
}


# Send the POST request
response = requests.post(url, headers=headers, json=data)


# Print the response
result = response.json()
print(result['choices'][0]['message']['content'])

"""## **Conclusion :**
This tool is a starting point for developing AI-powered solutions for civic education and policy exploration, empowering users to deepen their knowledge and contribute to shaping government.
"""